### ISSUE TITLE
User test new templates 

### ISSUE THREAD

**Issue by sdwilkes** [nationalarchives/tna-base#148]

**Comment by jklepfer** [comment]
Light touch testing script being written. Have booked testing for Thursday pm. Have asked Hari to take notes - if anyone else would like to join let me know!

**Comment by jklepfer** [comment]
Not many about in the reading rooms on Thursday but Beth and I nabbed one internal stakeholder for some testing. Here are the notes: 

User 1 
When shown the archives sector home page 
-	See the colours and font as an improvement
-	Prefers the new typography
-	Some sort of navigation is missing 
-	At present generally we ask people to do too many things
-	The mix of 2 or 3 in a column means – where does the eye go?
-	There is not enough to mark out each section
-	No real priority [of content? I think] 
-	Blue things – means things I can click. Especially the smaller ones 
-	Says it would be a nightmare to do images for – long thin images are tricky as most of our images are portrait
-	Difficult to see info/groupings as no boxes – not grouped so well 
-	Looks nice but have to work harder 

Publication/ content page
-	People need structure
-	Too loose
-	Older audience may need a bit more guidance
-	Find it more readable – like the type and black and white only is easier to read
-	Too much copy [generally] 
-	Looks a bit like a print doc – needs chunking up more 
-	Posh pull quote – not sure what purpose its serving. You need to use pull quote in the right way.
-	Absence of buttons

**Comment by jklepfer** [comment]
Off site testing (Newbury) on rebrand 5 July 2019  

H:\Documents\rebrand 1st user testing .docx

**Comment by jklepfer** [comment]
[rebrand 1st user testing .docx](https://github.com/nationalarchives/tna-base/files/3377764/rebrand.1st.user.testing.docx)

**Comment by sdwilkes** [comment]
Thanks @jklepfer :)

**Comment by jklepfer** [comment]
Did some more testing in Newbury on these pages: 
User testing on 
Prototype 1: http://tna-prototypes.s3-website-eu-west-1.amazonaws.com/tna-grid/level-one-cards.html
Prototype 2: http://tna-prototypes.s3-website-eu-west-1.amazonaws.com/tna-grid/level-two-img.html
Prototype 3: http://tna-prototypes.s3-website-eu-west-1.amazonaws.com/tna-grid/portal.html
USER 1 

USER 2

Newbury Library 

Retired man - been coming to Newbury library 77 years (!) so quite old
Was a machine minder in a cardboard factory until retirement 

does not use the internet

Prototype 1

To him it looks like it is, ‘to a large extent about history’

It makes sense to him - good images - although the one above the top left ‘card’ he doesn’t know what that is. 

Text is an okay size - even without his glasses he can make it out. 

USER 3

Male - financial advisor 
(50s) 
Uses the internet a LOT 

Doesn’t know TNA at all. 

Prototype 1
first thing he would do would be to try to interact with the big banner across the top as it is the biggest thing on the page. 

What he would really like is something that says clearly what the national archives is 

Readable

Good image to text balance

feels like it is about historical info 

Sees the search bar at the top but instead of ‘search our website’ why can’t it ask ‘what are you looking for?’

He didn’t see the red mega menu button. When asked he says he would ignore it (it didn’t catch his eye unprompted anyway) ands hope that all the info he would need would be in the page 

Once the mega menu opened he said it was just too much information - overwhelming.

USER 4 

Teacher

On the internet a LOT 

Member of the National Trust. 
Doesn’t go to art museums/other cultural institutions 

Prototype 3 

TNA brand header makes sense - she knows what site she is on.
She can read it all

Loves the photos in the banner - black and white - feels like it links to history and also to the topic (black history) 

First thing she would do is scroll down the page all the way to the bottom then she would click on the hyperlinks in the sub headings 

Says the mega menu doesn’t draw her eye - she would have expected it to be at the top left of the page from her experience using websites

Once opened the mega menu takes a while to read but she says she thinks the type of people who use TNA would probably be the type of people who would read that kind of thing. Says it is a bit overwhelming and might work better if you took the subheadings away until you clicked to open them (hide the text of the subsections)

**Comment by jklepfer** [comment]
@jklepfer  to test prototype 2 with users as well as the new prototypes @sdwilkes  will send across. 

Things to explore with users: 
     insight about use of images with cards 
     cards with multiple links vs single cards with single call to action 
     (GA with Helen Oake?)
